fix

diff --git a/develop/app-skeleton/.gitlab-ci.yml b/develop/app-skeleton/.gitlab-ci.yml
--- a/develop/app-skeleton/.gitlab-ci.yml
+++ b/develop/app-skeleton/.gitlab-ci.yml
@@ -106,7 +106,21 @@ build_and_push:
   script:
     - echo "Building and pushing image..."
     - buildah bud --storage-driver=vfs --format=${FORMAT} --tls-verify=false -t ${IMAGE} ${CONTEXT}
-    - buildah push --storage-driver=vfs --digestfile /tmp/image-digest --tls-verify=false --authfile /opt/quay-credentials/auth.json "${IMAGE}" "docker://${IMAGE}" 
+    - |
+      set +e
+      for i in {1..3}; do
+        echo "Attempt $i: Pushing image..."
+        buildah push --storage-driver=vfs --digestfile /tmp/image-digest --tls-verify=false --authfile /opt/quay-credentials/auth.json "${IMAGE}" "docker://${IMAGE}"
+        if [ $? -eq 0 ]; then
+          echo "Push succeeded!"
+          exit 0
+        else
+          echo "Push failed. Retrying in 10 seconds..."
+          sleep 10
+        fi
+      done
+      echo "Push failed after 3 attempts."
+      exit 1
 
 git-clone-manifests:
   stage: git-clone
